#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF AND APP CONFIG
#=================================================
ynh_script_progression "Updating the URL of $app..."

ynh_config_change_url_nginx

# The public base URL is embedded in the app config, so regenerate it.
ynh_config_add --template="hobopages.env" --destination="$install_dir/.env"
hobopages_fix_permissions

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="listening on" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
